name: btth3
channels:
  - defaults
dependencies:
  - python==3.10
  - numpy
  - requests
  - fastapi
  - black
  - isort
  - pylint
  - pytest
  - pre-commit
  - flake8
  - beautifulsoup4
  - sentence-transformers
  - pip:
      - google-genai
      - python-dotenv
      - coverage
      - weaviate-client