name: testing
channels:
  - defaults
dependencies:
  - numpy>=2.2.6
  - requests>=2.32.3
  - fastapi==0.115.9
  - black>=25.1.0
  - isort>=6.0.1
  - pylint>=3.3.7
  - pytest>=8.4.1
  - pre-commit>=4.2.0 
  - flake8>=7.2.0
  - beautifulsoup4>=4.13.4
  - sentence-transformers>=5.0.0
  - chromadb>=1.0.15
  - pip:
      - google-genai>=1.26.0
      - python-dotenv>=1.1.1
      - coverage>=7.9.2