name: Service CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          auto-activate-base: false
          activate-environment: testing 
          python-version: 3.13
          use-mamba: true

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files

      - name: Run retrieve tests with coverage
        run: |
          echo "Running tests for retrieve module"
          coverage run -m pytest tests/test_retrieve
          coverage report

      - name: Install Newman
        run: |
          npm install -g newman newman-reporter-html

      - name: Run Postman Integration Tests
        run: |
          ./run_newman.sh

      - name: Upload Newman HTML report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman_reports/report.html
